// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMeta.proto
package com.isa.grpc.protobuf;
public final class MyMetaOuterClass {
  private MyMetaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(MyMetaOuterClass.meta);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool isFact = 1;</code>
     * @return Whether the isFact field is set.
     */
    boolean hasIsFact();
    /**
     * <code>optional bool isFact = 1;</code>
     * @return The isFact.
     */
    boolean getIsFact();
  }
  /**
   * Protobuf type {@code MyMeta}
   */
  public static final class MyMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyMeta)
      MyMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMeta.newBuilder() to construct.
    private MyMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMeta() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMeta();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isFact_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyMetaOuterClass.internal_static_MyMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyMetaOuterClass.internal_static_MyMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMetaOuterClass.MyMeta.class, MyMetaOuterClass.MyMeta.Builder.class);
    }

    private int bitField0_;
    public static final int ISFACT_FIELD_NUMBER = 1;
    private boolean isFact_;
    /**
     * <code>optional bool isFact = 1;</code>
     * @return Whether the isFact field is set.
     */
    @java.lang.Override
    public boolean hasIsFact() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool isFact = 1;</code>
     * @return The isFact.
     */
    @java.lang.Override
    public boolean getIsFact() {
      return isFact_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isFact_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isFact_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMetaOuterClass.MyMeta)) {
        return super.equals(obj);
      }
      MyMetaOuterClass.MyMeta other = (MyMetaOuterClass.MyMeta) obj;

      if (hasIsFact() != other.hasIsFact()) return false;
      if (hasIsFact()) {
        if (getIsFact()
            != other.getIsFact()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsFact()) {
        hash = (37 * hash) + ISFACT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsFact());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMetaOuterClass.MyMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMetaOuterClass.MyMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMetaOuterClass.MyMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMetaOuterClass.MyMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMetaOuterClass.MyMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMeta)
        MyMetaOuterClass.MyMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyMetaOuterClass.internal_static_MyMeta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyMetaOuterClass.internal_static_MyMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMetaOuterClass.MyMeta.class, MyMetaOuterClass.MyMeta.Builder.class);
      }

      // Construct using MyMetaOuterClass.MyMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isFact_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyMetaOuterClass.internal_static_MyMeta_descriptor;
      }

      @java.lang.Override
      public MyMetaOuterClass.MyMeta getDefaultInstanceForType() {
        return MyMetaOuterClass.MyMeta.getDefaultInstance();
      }

      @java.lang.Override
      public MyMetaOuterClass.MyMeta build() {
        MyMetaOuterClass.MyMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MyMetaOuterClass.MyMeta buildPartial() {
        MyMetaOuterClass.MyMeta result = new MyMetaOuterClass.MyMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isFact_ = isFact_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMetaOuterClass.MyMeta) {
          return mergeFrom((MyMetaOuterClass.MyMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMetaOuterClass.MyMeta other) {
        if (other == MyMetaOuterClass.MyMeta.getDefaultInstance()) return this;
        if (other.hasIsFact()) {
          setIsFact(other.getIsFact());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyMetaOuterClass.MyMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyMetaOuterClass.MyMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isFact_ ;
      /**
       * <code>optional bool isFact = 1;</code>
       * @return Whether the isFact field is set.
       */
      @java.lang.Override
      public boolean hasIsFact() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool isFact = 1;</code>
       * @return The isFact.
       */
      @java.lang.Override
      public boolean getIsFact() {
        return isFact_;
      }
      /**
       * <code>optional bool isFact = 1;</code>
       * @param value The isFact to set.
       * @return This builder for chaining.
       */
      public Builder setIsFact(boolean value) {
        bitField0_ |= 0x00000001;
        isFact_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isFact = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFact() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isFact_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMeta)
    }

    // @@protoc_insertion_point(class_scope:MyMeta)
    private static final MyMetaOuterClass.MyMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMetaOuterClass.MyMeta();
    }

    public static MyMetaOuterClass.MyMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyMeta>
        PARSER = new com.google.protobuf.AbstractParser<MyMeta>() {
      @java.lang.Override
      public MyMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMeta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MyMetaOuterClass.MyMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int META_FIELD_NUMBER = 80412;
  /**
   * <pre>
   * numbering: search for "One last thing" in the link above
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      MyMetaOuterClass.MyMeta> meta = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        MyMetaOuterClass.MyMeta.class,
        MyMetaOuterClass.MyMeta.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MyMeta.proto\032 google/protobuf/descript" +
      "or.proto\"\030\n\006MyMeta\022\016\n\006isFact\030\001 \001(\010:6\n\004me" +
      "ta\022\035.google.protobuf.FieldOptions\030\234\364\004 \001(" +
      "\0132\007.MyMeta"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_MyMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMeta_descriptor,
        new java.lang.String[] { "IsFact", });
    meta.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
